In [1]:
from sklearn import svm,datasets
digits = datasets.load_digits()

In [2]:
import pandas as pd
df = pd.DataFrame(digits.data,columns = digits.feature_names)
df['target'] = digits.target
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [4]:
from sklearn.model_selection import cross_val_score

In [5]:
import numpy as np
kernels = ['rbf','linear']
C=[1,10,20]
avg_scores={}
for k_val in kernels:
    for c_val in C:
        cv_scores = cross_val_score(svm.SVC(kernel=k_val,C=c_val,gamma='auto'),digits.data,digits.target,cv=5)
        avg_scores[k_val+'_'+str(c_val)]=np.average(cv_scores)
avg_scores

{'rbf_1': 0.448545341999381,
 'rbf_10': 0.47636645001547506,
 'rbf_20': 0.47636645001547506,
 'linear_1': 0.9476973073351903,
 'linear_10': 0.9476973073351903,
 'linear_20': 0.9476973073351903}

In [6]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

clf.fit(digits.data,digits.target)
clf.cv_results_

{'mean_fit_time': array([0.15604949, 0.01600308, 0.14720078, 0.01540451, 0.14666362,
        0.01540484]),
 'std_fit_time': array([0.01639557, 0.00082412, 0.00066715, 0.00053422, 0.00026487,
        0.0005078 ]),
 'mean_score_time': array([0.04333391, 0.00458045, 0.05175567, 0.0042902 , 0.05166092,
        0.0042851 ]),
 'std_score_time': array([5.67709833e-05, 2.68241369e-04, 9.90567653e-05, 1.12422144e-04,
        7.61936840e-05, 1.15028700e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.41111111, 0.96388889, 0.45277778, 0.96388889, 0.45277778,
        0.96388889]),
 'split1_test_score': array([0.45      , 0.91944444, 0.46944444, 0.91944444, 0.46944444,
        0.91944444]),
 'split2_test_score': array([0.454039  , 0.96657382, 0.47910864, 0.96657382, 0.47910864,
        0.96657382]),
 'split3_test_score': array([0.44846797, 0.9637883 , 0.47910864, 0.9637883 , 0.47910864,
        0.9637883 ]),
 'split4_test_score': array([0.47910864, 0.92479109, 0.50139276, 0.92479109, 0.50139276,
        0.92479109]),
 'mean_test_score': array([0.44854534, 0.94769731, 0.47636645, 0.94769731, 0.47636645,
        0.94769731]),
 'std_test_score': array([0.02176115, 0.02097775, 0.01578414, 0.02097775, 0.01578414,
        0.02097775]),
 'rank_test_score': array([6, 1, 4, 1, 4, 1], dtype=int32)}

In [7]:
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.156049,0.016396,0.043334,0.000057,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.411111,0.450000,0.454039,0.448468,0.479109,0.448545,0.021761,6
1,0.016003,0.000824,0.004580,0.000268,1,linear,"{'C': 1, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1
2,0.147201,0.000667,0.051756,0.000099,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.452778,0.469444,0.479109,0.479109,0.501393,0.476366,0.015784,4
3,0.015405,0.000534,0.004290,0.000112,10,linear,"{'C': 10, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1
4,0.146664,0.000265,0.051661,0.000076,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.452778,0.469444,0.479109,0.479109,0.501393,0.476366,0.015784,4
5,0.015405,0.000508,0.004285,0.000115,20,linear,"{'C': 20, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1

In [9]:
df[['param_C','param_kernel','mean_test_score','rank_test_score']]

  param_C param_kernel  mean_test_score  rank_test_score
0       1          rbf         0.448545                6
1       1       linear         0.947697                1
2      10          rbf         0.476366                4
3      10       linear         0.947697                1
4      20          rbf         0.476366                4
5      20       linear         0.947697                1

In [11]:
clf.best_score_

0.9476973073351903

In [12]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [13]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [21]:
model_params = {
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    },
    'gaussian_naive_bayes':{
        'model':GaussianNB(),
        'params':{}
    },
    'multinomial_naive_bayes':{
        'model':MultinomialNB(),
        'params':{}
    },
    'decision_tree':{
        'model':DecisionTreeClassifier(),
        'params':{
            'criterion':['gini','entropy']
        }
    }
}

In [22]:
scores = []
for model_name,mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(digits.data,digits.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })

In [23]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

                     model  best_score                   best_params
0                      svm    0.947697  {'C': 1, 'kernel': 'linear'}
1            random_forest    0.909325          {'n_estimators': 10}
2      logistic_regression    0.922114                      {'C': 1}
3     gaussian_naive_bayes    0.806928                            {}
4  multinomial_naive_bayes    0.870350                            {}
5            decision_tree    0.811383      {'criterion': 'entropy'}